# Copyright (c) 2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# registry internal url
{{- $registry_internal_url := printf "http://registry.%s.svc.cluster.local:%d" .Values.app.namespace (int .Values.registry.service.ports.api) }}
# auth server internal url
{{- $auth_server_internal_url := printf "http://auth-server.%s.svc.cluster.local:%d" .Values.app.namespace (int .Values.authServer.service.ports.api) }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-user-scopes-config
  namespace: {{ .Values.app.namespace }}
data:
  scopes.yml: |
{{ .Files.Get "files/scopes.yml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-common-config
  namespace: {{ .Values.app.namespace }}
data:
  AUTH_SERVER_URL: {{ $auth_server_internal_url | quote }}
  AUTH_SERVER_EXTERNAL_URL: {{ .Values.externalUrls.authServer | quote }}
  REGISTRY_BASE_URL: {{ $registry_internal_url | quote }}
  REGISTRY_URL: {{ .Values.externalUrls.registry | quote }}
  AUTH_PROVIDER: {{ .Values.authentication.provider | quote }}
  KEYCLOAK_ENABLED: {{ .Values.authentication.keycloak.enabled | quote }}
  KEYCLOAK_URL: {{ .Values.authentication.keycloak.internalUrl | quote }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.externalUrls.keycloak | quote }}
  KEYCLOAK_ADMIN_URL: {{ .Values.externalUrls.keycloak | quote }}
  KEYCLOAK_REALM: {{ .Values.authentication.keycloak.realm | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.authentication.keycloak.clients.webClientId | quote }}
  KEYCLOAK_M2M_CLIENT_ID: {{ .Values.authentication.keycloak.clients.cliClientId | quote }}
  HEALTH_CHECK_INTERVAL_SECONDS: {{ .Values.registry.service.healthCheck.intervalSeconds | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-servers-seed-data
  namespace: {{ .Values.app.namespace }}
data:
  gerrit-mcp-server.json: |
{{ .Files.Get "files/servers/gerrit-mcp-server.json" | nindent 4 }}
